apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  labels:
    app: jellyfin
spec:
  destination:
    namespace: jellyfin
    server: https://kubernetes.default.svc
  project: media
  sources:
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops"
      path: clusters/helheim/workloads/media/jellyfin/manifests
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
