apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  labels:
    app: infisical
    project: core
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  project: core
  sources:
    - chart: secrets-operator
      repoURL: "https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts"
      targetRevision: 0.10.9
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true
