apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: whoami
  namespace: argocd
spec:
  description: Whoami test project for Envoy Gateway
  sourceRepos:
    - "*"
  destinations:
    - namespace: whoami
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
