apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  labels:
    app: core
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: core
  sources:
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops"
      path: clusters/helheim/core/gateway-api-crds/manifests
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
