apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: pomerium
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes-j8-fh
        secretName: POMERIUM_CLUSTER_TOKEN
        envSlug: helheim
        secretsPath: "/"
      credentialsRef:
        secretName: secret-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: pomerium
      secretNamespace: pomerium-zero
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          pomerium_zero_token: "{{ .POMERIUM_CLUSTER_TOKEN.Value }}"
