---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-patch
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  refreshInterval: "1h"
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      data:
        oidc.azure.clientSecret: "{{ .clientsecret }}"
  data:
    - secretKey: clientsecret
      remoteRef:
        key: ARGOCD_AZURE_ENTRA_CLIENT_SECRET
