apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "argocd.houseofix.online"
spec:
  parentRefs:
    - name: gateway-unencrypted
      namespace: nginx-gateway-fabric
  hostnames:
    - "argocd.houseofix.online"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
