apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: secret-argocd-sso-client-secret
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes-j8-fh
        secretName: ARGOCD_AZURE_ENTRA_CLIENT_SECRET
        envSlug: helheim
        secretsPath: "/"
      credentialsRef:
        secretName: secret-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: argocd-secret-copy
      secretNamespace: argocd
      creationPolicy: "Merge"
      template:
        includeAllSecrets: false
        data:
          clientsecret: "{{ .ARGOCD_AZURE_ENTRA_CLIENT_SECRET.Value }}"
