apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  refreshInterval: "1h"
  target:
    name: secret-cloudflared-tunnel-token
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARED_TUNNEL_TOKEN
