apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    app: external-secrets
    project: core
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: core
  sources:
    - chart: external-secrets
      repoURL: "https://charts.external-secrets.io"
      targetRevision: 0.20.3
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops.git"
      path: clusters/helheim/core/external-secrets/manifests
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true
