apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-private
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: root-private
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: clusters/helheim
    repoURL: "git@github.com:MichielVanHerreweghe/gitops-private.git"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
