apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: root
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: clusters/helheim
    repoURL: "https://github.com/MichielVanHerreweghe/gitops"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
