apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: An ArgoCD project for core cluster components
  sourceRepos:
    - "*"
    - https://github.com/MichielVanHerreweghe/gitops
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
