apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    app: external-dns
    project: core
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  project: core
  sources:
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops.git"
      path: clusters/helheim/core/external-dns/manifests
      targetRevision: HEAD
    - chart: external-dns
      repoURL: "https://kubernetes-sigs.github.io/external-dns/"
      targetRevision: 1.19.0
      helm:
        valueFiles:
          - $values/clusters/helheim/core/external-dns/values.yaml
    - repoURL: "https://github.com/MichielVanHerreweghe/gitops.git"
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
      - PruneLast=true
