apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - l2-announcement-policy.yaml
  - bgp-cluster-config.yaml
  - bgp-peer-config.yaml
  - bgp-advertisement.yaml
  - ip-pool.yaml
