apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: secret-cloudflare-api-key
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes-j8-fh
        secretName: CLOUDFLARE_API_KEY
        envSlug: helheim
        secretsPath: "/"
      credentialsRef:
        secretName: secret-machine-identity
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: secret-cloudflare-api-key
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          api-key: "{{ .CLOUDFLARE_API_KEY.Value }}"
