serviceAccount:
  create: true

nginx:
  service:
    type: LoadBalancer
  extraVolumeMounts:
    - name: nginx-config-override
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf

extraVolumes:
  - name: nginx-config-override
    configMap:
      name: nginx-gateway-config-override

gateways:
  - name: gateway-encrypted
    namespace: nginx-gateway-fabric
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      cert-manager.io/issue-temporary-certificate: "true"
      external-dns.alpha.kubernetes.io/target: "ip.houseofix.online"
    spec:
      gatewayClassName: nginx
      listeners:
        - name: https
          port: 443
          protocol: HTTPS
          hostname: "test.houseofix.online"
          allowedRoutes:
            namespaces:
              from: All
          tls:
            mode: Terminate
            certificateRefs:
              - name: tls-gateway-encrypted
                namespace: nginx-gateway-fabric
  - namespace: nginx-gateway-fabric
    name: gateway-unencrypted
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      cert-manager.io/issue-temporary-certificate: "true"
      external-dns.alpha.kubernetes.io/target: "ip.houseofix.online"
    spec:
      gatewayClassName: nginx
      listeners:
        - name: argocd-https
          port: 443
          protocol: HTTPS
          hostname: "argocd.houseofix.online"
          allowedRoutes:
            namespaces:
              from: All
          tls:
            mode: Terminate
            certificateRefs:
              - name: tls-gateway-unencrypted-argocd
                namespace: nginx-gateway-fabric
        - name: jellyfin-https
          port: 443
          protocol: HTTPS
          hostname: "jellyfin.houseofix.online"
          allowedRoutes:
            namespaces:
              from: All
          tls:
            mode: Terminate
            certificateRefs:
              - name: tls-gateway-unencrypted-jellyfin
                namespace: nginx-gateway-fabric
